### ISSUE TITLE
Getting load error

### ISSUE THREAD

**Issue by mvolz** [abartov/wimgs#5]
```
ruby wimgs.rb --wiki commons.wikimedia.org --category "Same category" --images-dir /home/my/path
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mediawiki_api (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from wimgs.rb:11:in `<main>'
```

**Comment by abartov** [comment]
You do need to install the Mediawiki API gem:

``` bash
gem install mediawiki_api
```

I'll update the README to mention that, when I get near a decent keyboard.
